### ISSUE TITLE
juan - Incorrect fee calculation when selling/burning a DVP position

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-smilee-finance-judging#29]
juan

high

# Incorrect fee calculation when selling/burning a DVP position

## Summary
The wrong parameter is passed into `FeeManager::tradeSellFee()` and this leads to incorrect fee calculation within `DVP::_burn()`

## Vulnerability Detail
In [`DVP::_burn()`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/DVP.sol#L290-L297), the fee is calculated in the following way:

```solidity
(uint256 fee, uint256 vaultFee) = feeManager.tradeSellFee(
        address(this),
        expiry,
        amount.up + amount.down,
        paidPayoff,
        entryPremiumProp,
        _baseTokenDecimals
);
```

The `IFeeManager::tradeSellFee` function states that the second-last parameter should be the entry premium. However in the above code snippet, entryPremiumProp is used instead.

<details>
<summary>Natspec for IFeeManager::tradeSellFee()</summary>

```javascript
/**
        Computes trade fee for selling options
        @param dvp The address of the DVP on which the trade is being performed
        @param expiry The expiry timestamp of current epoch of the DVP
        @param notional The notional of the traded option
        @param currPremium The current premium of the traded option (user payoff)
---->   @param entryPremium The premium paid for the option
        @param tokenDecimals # of decimals in the notation of the option base token
        @return fee The required fee
        @return minFee The required minimum fee paid for each trade which is transferred to the vault

     */
    function tradeSellFee(
        address dvp,
        uint256 expiry,
        uint256 notional,
        uint256 currPremium,
        uint256 entryPremium,
        uint8 tokenDecimals
    ) external view returns (uint256 fee, uint256 minFee);
```
</details>

<details>
<summary> Implementation of FeeManager::tradeSellFee() </summary>

```solidity
function tradeSellFee(
        address dvp,
        uint256 expiry,
        uint256 notional,
        uint256 currPremium,
        uint256 entryPremium,
        uint8 tokenDecimals
    ) external view returns (uint256 fee, uint256 minFee) {
        fee = _getFeeFromNotionalAndPremium(dvp, notional, currPremium, tokenDecimals, block.timestamp > expiry);

        if (currPremium > entryPremium) {
            uint256 pnl = currPremium - entryPremium;
            pnl = AmountsMath.wrapDecimals(pnl, tokenDecimals);
            uint256 successFee = pnl.wmul(_dvpsFeeParams[dvp].successFeeTier.get());
            successFee = AmountsMath.unwrapDecimals(successFee, tokenDecimals);

            fee += successFee;
        }

        minFee = _minFee(dvp, expiry);
        fee += minFee;
    }
```
</details>

In the above implementation, even if PnL is negative, the `currPremium > entryPremium` condition will still execute (since `entryPremiumProp` is passed in instead of `entryPremium`. Then the successFee will be calculated even though the trade was not succesful, causing even more fund loss for traders.

> Note: If somehow this is actually intended behaviour, and the code comment is supposed to be `entryPremiumProp`, then the tradeSellFee calculated within `DVP::payoff()` is incorrect since it uses the entry premium when calculating tradeFee rather than using entryPremiumProp.

## Impact

The successFee calculated within the `tradeSellFee` function will be inflated incorrectly due to PnL being inflated incorrectly. Because of this, the fees calculated are much higher than what is correct, so traders are much less incentivised to participate here due to the breaking of core protocol functionality.

## Code Snippet
https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/interfaces/IFeeManager.sol#L23-L42

https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/DVP.sol#L295

## Tool used
Manual Review

## Recommendation
Use `position.premium` rather than `entryPremiumProp` as the `entryPremium` parameter for the `FeeManager::tradeSellFee()` function.
```diff
(uint256 fee, uint256 vaultFee) = feeManager.tradeSellFee(
        address(this),
        expiry,
        amount.up + amount.down,
        paidPayoff,
-       entryPremiumProp,
+       position.premium,
        _baseTokenDecimals
);
```

**Comment by 0xjuaan** [comment]
Escalate

Even if it makes more sense to calculate fee from only the closing part of the position's premium, the value is treated incorrectly within `FeeManager.tradeSellFee()`-

```solidity
    function tradeSellFee(
        address dvp,
        uint256 expiry,
        uint256 notional,
        uint256 currPremium,
        uint256 entryPremium,
        uint8 tokenDecimals
    ) external view returns (uint256 fee, uint256 minFee) {
        fee = _getFeeFromNotionalAndPremium(dvp, notional, currPremium, tokenDecimals, block.timestamp > expiry);


        if (currPremium > entryPremium) { //-----> THIS IS WRONG!!!
            uint256 pnl = currPremium - entryPremium; //-----> AS A RESULT, THIS IS WRONG!!!
            pnl = AmountsMath.wrapDecimals(pnl, tokenDecimals);
            uint256 successFee = pnl.wmul(_dvpsFeeParams[dvp].successFeeTier.get());
            successFee = AmountsMath.unwrapDecimals(successFee, tokenDecimals);


            fee += successFee;
        }


        minFee = _minFee(dvp, expiry);
        fee += minFee;
    }
```
    
It calculated `pnl` as `currPremium-entryPremium`. But `entryPremium` parameter is actually the `entryPremiumProp` which can be much smaller than `currPremium`. It does not make any sense to use `entryPremiumProp` and compare it to `currPremium` in calculation of PnL. This would lead to PnL being inflated severely and unfair amounts of fees charged to the user (this is explained in the impact section of my submission).

Permalink to code mentioned is [here](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/FeeManager.sol#L147-L168)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Even if it makes more sense to calculate fee from only the closing part of the position's premium, the value is treated incorrectly within `FeeManager.tradeSellFee()`-
> 
> ```solidity
>     function tradeSellFee(
>         address dvp,
>         uint256 expiry,
>         uint256 notional,
>         uint256 currPremium,
>         uint256 entryPremium,
>         uint8 tokenDecimals
>     ) external view returns (uint256 fee, uint256 minFee) {
>         fee = _getFeeFromNotionalAndPremium(dvp, notional, currPremium, tokenDecimals, block.timestamp > expiry);
> 
> 
>         if (currPremium > entryPremium) { //-----> THIS IS WRONG!!!
>             uint256 pnl = currPremium - entryPremium; //-----> AS A RESULT, THIS IS WRONG!!!
>             pnl = AmountsMath.wrapDecimals(pnl, tokenDecimals);
>             uint256 successFee = pnl.wmul(_dvpsFeeParams[dvp].successFeeTier.get());
>             successFee = AmountsMath.unwrapDecimals(successFee, tokenDecimals);
> 
> 
>             fee += successFee;
>         }
> 
> 
>         minFee = _minFee(dvp, expiry);
>         fee += minFee;
>     }
> ```
>     
> It calculated `pnl` as `currPremium-entryPremium`. But `entryPremium` parameter is actually the `entryPremiumProp` which can be much smaller than `currPremium`. It does not make any sense to use `entryPremiumProp` and compare it to `currPremium` in calculation of PnL. This would lead to PnL being inflated severely and unfair amounts of fees charged to the user (this is explained in the impact section of my submission).
> 
> Permalink to code mentioned is [here](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/FeeManager.sol#L147-L168)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
@0xjuaan 
This is intended behaviour: pnl is calculated only from the part of the position which is being closed, not from the whole position. It doesn't make any sense to use full position premium to calculate pnl if you close, for example, only 1% of the position size. If what you propose to do is implemented, this will create all kinds of issues: user avoiding paying the success fee, or paying inflated fee, or paying it multiple times.
This is intended flow:

1. Open position size = 400, premium paid = 4
2. Close position size = 100, premium received = 2. pnl = 2 - 1 = +1 (remaining position premium = 3)
3. Close position size = 100, premium received = 2. pnl = 2 - 1 = +1 (remaining position premium = 2)
4. Close position size = 100, premium received = 1, pnl = 1 - 1 = 0 (remaining position premium = 1)
5. Close position size = 100, premium received = 1, pnl = 1 - 1 = 0 (fully closed)

So a total premium paid = 4, total premium received = 6. Total profit = +2 (and success fee paid from +2)

Now let's see what happens if what you think is the correct flow:
1. Open position size = 400, premium paid = 4
2. Close position size = 100, premium received = 2. pnl = 2 - 4 = -2 (remaining position premium = 3)
3. Close position size = 100, premium received = 2. pnl = 2 - 3 = -1 (remaining position premium = 2)
4. Close position size = 100, premium received = 1, pnl = 1 - 2 = -1 (remaining position premium = 1)
5. Close position size = 100, premium received = 1, pnl = 1 - 1 = 0 (fully closed)

So in this case it's the same = received 6, paid 4, profit should be +2. However, from the calculations pnl is -4 and no success fee is paid.

So what you suggest doesn't make any sense. And the way it is now is correct and intended. Like I said in the judging comment - the `payoff` function is indeed incorrect, but it's a view function not used in the protocol itself and thus invalid (low) by sherlock rules.

**Comment by 0xjuaan** [comment]
You are right, thank you for the detailed explanation. I thought `currPremium` meant the current premium but it turns out to be the premium received (aka payoff).

However since `payoff()` calculates incorrect payoff information, maybe sponsors should know about it in case that function is used to query data for the front-end

**Comment by cvetanovv** [comment]
I agree with panprog comment and the sponsor is already aware of the `payoff()` function.

**Comment by Czar102** [comment]
Agree, planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-02-smilee-finance-judging/issues/29/#issuecomment-2003796493): rejected
